<?php
 
function news_node_info() {
	return array(
		'news' => array(
			'name' => 'News',
			'base' => 'news',
			'description' => t('News Content Type'),
			'has_title' => True,
			'title_label' => t('News Title'),
		),
	);
}

function news_form($node, $form_state) {
	return node_content_form($node, $form_state);
}

// function news_views_api() {
// 	return array(
// 		'api' => '3.0',
// 	);
// }

// function news_views_default_views() {
// 	$path = drupal_get_path('module', 'news') . '/views/*.inc';
// 	$views = array();
// 	foreach (glob($path) as $views_filename) {
// 		require_once($views_filename);
// 	}
// 	return $views;
// }